name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Generate coverage report
    - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.1.2'
    - name: Install dependencies
      run: poetry install
    - name: Run tests
      run: poetry run pytest --cov=./ --cov-report=xml .
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/